global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'central-core'
    static_configs:
      - targets: ['central-core:8000']
  
  - job_name: 'agent-node'
    static_configs:
      - targets: ['agent-node:8001']
